name: Create Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP archive
        run: zip -r mypackage.zip .

      - name: Create TAR archive
        run: tar -czf mypackage.tar.gz .

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mypackage.zip
            mypackage.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
